### ISSUE TITLE
add fund and department descriptions

### ISSUE THREAD

**Issue by derekeder** [derekeder/oak-park-budget#5]
To add context to the budget numbers, draft descriptions for funds and departments. This info can be organized in a separate spreadsheet and linked to by Fund ID and Department ID.

When done, merge in to our main sheet in `cleanup.py`

**Comment by achastain** [comment]
I have started a [spreadsheet](https://docs.google.com/spreadsheets/d/1BHhgl0wZn9AHCh4f8OL6n8pcI707RCJbg_YKttS-qIM/edit?usp=sharing) with these descriptions. It has the departments so far. I can add funds to if needed.

**Comment by derekeder** [comment]
@achastain i've added these in with #12  and they're now being displayed: 

![Screen Shot 2021-03-18 at 12 24 58 PM](https://user-images.githubusercontent.com/919583/111669617-fbb26d80-87e4-11eb-94cf-00cbacca2393.png)


I think adding Fund descriptions would be helpful!

**Comment by derekeder** [comment]
closed via #12
